version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./tictactoe:/tictactoe
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"